apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    commit.image.appsody.dev/contextDir: /Users/jeromeboyer/code/AllCloudPaks/vaccine-order-optimizer
    commit.image.appsody.dev/date: Fri Sep 25 08:22:57 2020 -0700
    commit.image.appsody.dev/message: 'Merge pull request #1 from jesusmah/master'
    commit.stack.appsody.dev/contextDir: /incubator/python-flask
    commit.stack.appsody.dev/date: Tue Jun 16 13:12:10 2020 +0100
    commit.stack.appsody.dev/message: 'python-flask: Avoid permission errors when
      building dependencies (#834)'
    image.opencontainers.org/created: "2021-01-13T21:10:20-08:00"
    image.opencontainers.org/documentation: https://github.com/ibm-cloud-architecture/vaccine-order-optimizer
    image.opencontainers.org/revision: e509f343dc7f7ebbe2340c01cc510a47b83d545e-modified
    image.opencontainers.org/source: https://github.com/ibm-cloud-architecture/vaccine-order-optimizer/tree/master
    image.opencontainers.org/url: https://github.com/ibm-cloud-architecture/vaccine-order-optimizer
    stack.appsody.dev/authors: Chris Bailey <seabaylea>, Henry Nash <henrynash>
    stack.appsody.dev/configured: docker.io/appsody/python-flask:latest
    stack.appsody.dev/created: "2020-06-16T12:14:33Z"
    stack.appsody.dev/description: Flask web Framework for Python
    stack.appsody.dev/digest: sha256:2113962fbbb33dd895cdfc878a501b65799737e4dbe688dc9da0de9c7c050218
    stack.appsody.dev/documentation: https://github.com/appsody/stacks/tree/master/incubator/python-flask/README.md
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/revision: fe8e2b8701074199dcf3ecb549ff2a40f7611d8c
    stack.appsody.dev/source: https://github.com/appsody/stacks/tree/master/incubator/python-flask/image
    stack.appsody.dev/tag: docker.io/appsody/python-flask:0.2.4
    stack.appsody.dev/title: Python Flask
    stack.appsody.dev/url: https://github.com/appsody/stacks/tree/master/incubator/python-flask
  creationTimestamp: null
  labels:
    app.kubernetes.io/part-of: covid19-vaccine
    image.opencontainers.org/title: vaccine-order-optimizer
    stack.appsody.dev/id: python-flask
    stack.appsody.dev/version: 0.2.4
  name: vaccine-order-optimizer
spec:
  applicationImage: dev.local/vaccine-order-optimizer
  createKnativeService: false
  env:
  - name: KAFKA_BROKERS
    valueFrom:
      configMapKeyRef:
        key: brokers
        name: vaccine-oro-cm
  - name: REEFER_TOPIC
    valueFrom:
      configMapKeyRef:
        key: reeferTopic
        name: vaccine-oro-cm
  - name: INVENTORY_TOPIC
    valueFrom:
      configMapKeyRef:
        key: inventoryTopic
        name: vaccine-oro-cm
  - name: TRANSPORTATION_TOPIC
    valueFrom:
      configMapKeyRef:
        key: transportationTopic
        name: vaccine-oro-cm
  - name: KAFKA_USER
    valueFrom:
      secretKeyRef:
        key: username
        name: eventstreams-cred
  - name: KAFKA_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: eventstreams-cred
  - name: KAFKA_CERT
    value: /certs/es-cert.pem
  - name: PYTHONUNBUFFERED
    value: "yes"
  - name: JSONIFY_PRETTYPRINT_REGULAR
    value: "True"
  - name: FLASK_DEBUG
    value: "False"
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  monitoring:
    labels:
      k8s-app: vaccine-order-optimizer
  pullPolicy: Always
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 8080
    type: NodePort
  stack: python-flask
  version: 1.0.0
  volumeMounts:
  - mountPath: /certs
    name: eventstreams-cert-pem
  volumes:
  - name: eventstreams-cert-pem
    secret:
      secretName: eventstreams-cert-pem
