version: '2'
services:
  zookeeper:
    image: strimzi/kafka:latest-kafka-2.6.0
    hostname: zookeeper
    container_name: zookeeper
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    image: strimzi/kafka:latest-kafka-2.6.0
    hostname: kafka
    container_name: kafka
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  apicurio:
    hostname: apicurio
    container_name: apicurio
    image: apicurio/apicurio-registry-mem
    ports:
      - 8080:8080
  optimizer:
    image: ibmcase/vaccine-order-optimizer
    container_name: optimizer
    depends_on:
      - kafka
    ports:
      - 5000:5000
    environment:
      KAFKA_BROKERS: kafka:9092
      SCHEMA_REGISTRY_URL: http://apicurio:8080/api
      INVENTORY_TOPIC: vaccine.inventory
      REEFER_TOPIC: vaccine.reefers
      TRANSPORTATION_TOPIC: vaccine.transportation
      ORDER_TOPIC: vaccine.orderevents
