apiVersion: v1
kind: Service
metadata:
  name: vaccine-order-optimizer
  namespace: vaccine
  labels:
    name: vaccine-order-optimizer
    app: vaccine-order-optimizer
spec:
  ports:
    - name: web
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: vaccine-order-optimizer
  type: ClusterIP
  sessionAffinity: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: vaccine-order-optimizer
  namespace: vaccine
  labels:
    app: vaccine-order-optimizer
spec:
  path: /
  to:
    kind: Service
    name: vaccine-order-optimizer
    weight: 100
  port:
    targetPort: 5000
  wildcardPolicy: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaccine-order-optimizer
  namespace: vaccine
  labels:
    app: vaccine-order-optimizer
spec:
  selector:
    matchLabels:
      app: vaccine-order-optimizer
  replicas: 1
  template:
    metadata:
      labels:
        app: vaccine-order-optimizer
    spec:
      containers:
      - name: vaccine-order-optimizer
        image: ibmcase/vaccine-order-optimizer
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
          - name: APP_VERSION
            valueFrom:
              configMapKeyRef:
                key: app-version
                name: vaccine-oro-cm
          - name: SCHEMA_REGISTRY_URL
            valueFrom:
              secretKeyRef:
                key: SCHEMA_REGISTRY_URL
                name: vaccine-oro-secrets
          - name: KAFKA_BROKERS
            valueFrom:
              configMapKeyRef:
                key: brokers
                name: vaccine-oro-cm
          - name: REEFER_TOPIC
            valueFrom:
              configMapKeyRef:
                key: reeferTopic
                name: vaccine-oro-cm
          - name: INVENTORY_TOPIC
            valueFrom:
              configMapKeyRef:
                key: inventoryTopic
                name: vaccine-oro-cm
          - name: TRANSPORTATION_TOPIC
            valueFrom:
              configMapKeyRef:
                key: transportationTopic
                name: vaccine-oro-cm
          - name: KAFKA_USER
            value: jesus-dev
          - name: KAFKA_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: jesus-dev
          - name: KAFKA_CERT
            value: "/app/certs/es-cert.pem"
          - name: PYTHONUNBUFFERED
            value: "yes"
          - name: JSONIFY_PRETTYPRINT_REGULAR
            value: "True"
          - name: FLASK_DEBUG
            value: "False"
        expose: true
        volumeMounts:
            - name: eventstreams-pem
              mountPath: /app/certs
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 2
        monitoring:
          labels:
            k8s-app: vaccine-order-optimizer
        pullPolicy: Always
        service:
          annotations:
            prometheus.io/scrape: "true"
          port: 8080
          type: NodePort
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
      volumes:
      - name: eventstreams-pem
        secret:
          secretName: eda-es-pem
          