kind: ConfigMap
apiVersion: v1
metadata:
  name: vaccine-oro-cm
  namespace: vaccine
data:
  KAFKA_BROKERS: gse-eda-dev-kafka-bootstrap-eventstreams.eventstreams.svc:9093
  # KAFKA_BROKERS: broker-1-tdp3907dtr3p4gn4.kafka.svc06.us-south.eventstreams.cloud.ibm.com:9093,broker-2-tdp3907dtr3p4gn4.kafka.svc06.us-south.eventstreams.cloud.ibm.com:9093,broker-4-tdp3907dtr3p4gn4.kafka.svc06.us-south.eventstreams.cloud.ibm.com:9093,broker-3-tdp3907dtr3p4gn4.kafka.svc06.us-south.eventstreams.cloud.ibm.com:9093,broker-5-tdp3907dtr3p4gn4.kafka.svc06.us-south.eventstreams.cloud.ibm.com:9093,broker-0-tdp3907dtr3p4gn4.kafka.svc06.us-south.eventstreams.cloud.ibm.com:9093
  INVENTORY_TOPIC: vaccine-inventory
  TRANSPORTATION_TOPIC: vaccine-transportation
  REEFER_TOPIC: vaccine-reefer
  APP_VERSION: v0.0.3
  CONSUMER_GRP: vaccine-optimizer