apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaccine-order-optimizer
  labels:
    app: vaccine-order-optimizer
spec:
  selector:
    matchLabels:
      app: vaccine-order-optimizer
  replicas: 1
  template:
    metadata:
      labels:
        app: vaccine-order-optimizer
    spec:
      containers:
      - name: vaccine-order-optimizer
        image: quay.io/ibmcase/vaccine-order-optimizer
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
        envFrom:
          - configMapRef:
              name: vaccine-oro-cm
          - configMapRef:
              name: kafka-topics-cm
          - secretRef:
              name: kafka-schema-registry
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
        env:
          - name: KAFKA_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: scram-user 
          - name: KAFKA_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: scram-user 
          - name: KAFKA_CERT
            value: "/app/certs/ca.crt"
          - name: PYTHONUNBUFFERED
            value: "yes"
          - name: JSONIFY_PRETTYPRINT_REGULAR
            value: "True"
          - name: FLASK_DEBUG
            value: "False"
          - name: DEBUG_OPTIMIZATION
            value: "False"
        expose: true
        volumeMounts:
            - name: kafka-cert
              mountPath: /app/certs
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 2
        monitoring:
          labels:
            k8s-app: vaccine-order-optimizer
        pullPolicy: Always
        service:
          annotations:
            prometheus.io/scrape: "true"
          port: 8080
          type: NodePort
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
      volumes:
      - name: kafka-cert
        secret:
          secretName: kafka-cluster-ca-cert
          